# Generated by Django 4.2.3 on 2023-07-28 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_created_date_alter_user_last_time_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 50, 8, 837502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_time_online',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 50, 8, 837502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 50, 8, 837502, tzinfo=datetime.timezone.utc)),
        ),
    ]
