# Generated by Django 4.2.3 on 2023-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('os', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.IntegerField(default=8)),
                ('video_card', models.CharField(max_length=50)),
                ('direct_x', models.CharField(max_length=50)),
                ('disk_space', models.IntegerField()),
            ],
            options={
                'db_table': 'SystemRequirements',
            },
        ),
    ]
