# Generated by Django 4.2.3 on 2023-07-28 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 50, 8, 838499, tzinfo=datetime.timezone.utc)),
        ),
    ]
