# Generated by Django 4.2.3 on 2023-07-28 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_desired_games', '0003_alter_userdesiredgames_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesiredgames',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 39, 13, 824190, tzinfo=datetime.timezone.utc)),
        ),
    ]
