# Generated by Django 4.2.3 on 2023-07-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_requirements', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.FloatField(default=0.0)),
                ('age_rating', models.CharField(max_length=10)),
                ('rating', models.FloatField(default=0.0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developer')),
                ('min_system_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_system_requirements', to='system_requirements.systemrequirement')),
                ('rec_system_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_system_requirements', to='system_requirements.systemrequirement')),
            ],
            options={
                'db_table': 'Games',
            },
        ),
    ]
