# Generated by Django 4.2.3 on 2023-07-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_alter_developer_table'),
        ('categories', '0002_alter_category_options'),
        ('games', '0002_game_category_alter_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='developers.developer'),
        ),
    ]
