# Generated by Django 4.2.3 on 2023-07-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_alter_developer_table'),
        ('games', '0003_alter_game_category_alter_game_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='developers.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
