# Generated by Django 4.2.3 on 2023-07-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_title'),
        ('games', '0004_remove_game_category_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
