# Generated by Django 4.2.3 on 2023-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'Publisher',
            },
        ),
    ]
