# Generated by Django 4.2.3 on 2023-07-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='Publishers',
        ),
    ]
